apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingpong-app-ingress
  annotations:
spec:
  ingressClassName: alb
  rules:
   - http:
      paths:
      - path: /ping
        pathType: Prefix
        backend:
          service:
            name: pingpong-app-service
            port:
              number: 3000
